((nil . ((php-project-root . "/home/username/git-repos/eccube-2_13")
	 (php-project-bootstrap-scripts . ((root . "tests/require.php")))
	 (phpstan-executable . "/home/username/.composer/vendor/bin/phpstan")
         (phpstan-working-dir . "/home/username/git-repos/eccube-2_13")
         (phpstan-config-file . (root . "phpstan.neon"))
         (phpstan-level . 7)
	 (quickrun-option-cmd-alist . ((:command . "~/git-repos/eccube-2_13/data/vendor/bin/phpunit")
				       (:exec . ("%c -c ~/git-repos/eccube-2_13/phpunit.xml.dist %s"))
				       (:outputter . quickrun/phpunit-outputter))))))
