name: CI/CD for EC-CUBE
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-16.04 ]
        php: [ 5.4, 5.5, 5.6, 7.1, 7.2, 7.3 ]
        db: [ mysql, pgsql ]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup PHP
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}
    - name: Setup MySQL
      if: matrix.db == 'mysql'
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: '3307'
        container port: '3306'
        mysql version: '5.7'
        mysql database: 'myapp_test'
        mysql root password: 'password'
    - name: Setup PostgreSQL
      if: matrix.db == 'pgsql'
      uses: harmon758/postgresql-action@master
      with:
        postgresql version: '11'
        postgresql db: 'myapp_test'
        postgresql user: 'postgres'
        postgresql password: 'password'

    - name: Setup Composer
      uses: nanasess/composer-installer-action@master
    - name: Install to Composer
      run: composer install --no-interaction -o

    - name: Setup to EC-CUBE with MySQL
      if: matrix.db == 'mysql'
      env:
        DB: ${{ matrix.db }}
        USER: root
        DBUSER: root
        DBPASS: password
        DBNAME: myapp_test
        DBPORT: '3307'
        HTTP_URL: http://localhost:8085/
        HTTPS_URL: http://localhost:8085/
      run: |
        sudo apt-get install -y mysql-client
        ./eccube_install.sh ${DB}
    - name: Setup to EC-CUBE with PostgreSQL
      if: matrix.db == 'pgsql'
      env:
        DB: ${{ matrix.db }}
        DBUSER: postgres
        DBPASS: password
        DBNAME: myapp_test
        DBPORT: '5432'
        HTTP_URL: http://localhost:8085/
        HTTPS_URL: http://localhost:8085/
      run: |
        sudo apt-get install -y postgresql-client
        ./eccube_install.sh ${DB}

    - name: Run to PHPUnit
      run: data/vendor/bin/phpunit --exclude-group classloader
